### ISSUE TITLE
run OPT

### ISSUE THREAD

**Issue by dirkgr** [allenai/catwalk#29]
@lolipopshock wrote us a nice guide on how to get started here: https://docs.google.com/document/d/1lBHt5S0wMfLlNNNbXCSaNE4kJRTOjrY7GJ5nWG958FI

The short of it is, we'll do this on top of the Megatron/metaseq codebase, not on top of Huggingface. We should make it an optional "integration" for catwalk, like we have in Tango, because of all the dependencies it pulls in.

**Comment by ashim95** [comment]
Hi @dirkgr 
Is it possible to share the above document, perhaps it is not shared publicly?

Thanks,
-- ashim

**Comment by dirkgr** [comment]
Actually, this is no longer up to date. We now convert OPT to huggingface format, and just run Huggingface code. You can do this yourself with OPT models up to 66B. For the 175B, you have to request the model from Facebook, and convert it to Huggingface format yourself. Or find someone who did this and put it on BitTorrent, I guess. We are not allowed to share that version with you because of the OPT licensing, but I assure you it works if you can get your hands on that version: https://github.com/allenai/catwalk/blob/bd5ccfa172d1c24bd7b4af6b00a79a273f65ff61/catwalk/models/__init__.py#L115
