### ISSUE TITLE
Problem with the WandB workspace

### ISSUE THREAD

**Issue by dirkgr** [allenai/catwalk#36]
I have a reliable repro where the WandB workspace puts itself into a state that it can't recover from.

In this repo, on the `Fewshot` branch, I run `python experiments/num_shots.py -w wandb://allennlp/catwalk --batch_size 4`.

It will complain like this:
```
                               File "/home/dirkg/miniconda3/envs/catwalk/lib/python3.9/site-packages/tango/integrations/wandb/workspace.py", line
                             147, in step_starting
                                 raise StepStateError(
                             tango.common.exceptions.StepStateError: Step 'PredictStep-001-aUzzaKky7tw1rXhp38mMWuboeag8cCGw' is in unexpected
                             state 'running' If you are certain the step is not running somewhere else, delete the lock file at
                             /home/dirkg/.cache/tango/wandb_workspace/PredictStep-001-aUzzaKky7tw1rXhp38mMWuboeag8cCGw/lock.

Exception ignored in: <function BaseFileLock.__del__ at 0x7f401c167dc0>
Traceback (most recent call last):
  File "/home/dirkg/miniconda3/envs/catwalk/lib/python3.9/site-packages/filelock/_api.py", line 234, in __del__
  File "/home/dirkg/miniconda3/envs/catwalk/lib/python3.9/site-packages/filelock/_api.py", line 204, in release
  File "/home/dirkg/miniconda3/envs/catwalk/lib/python3.9/site-packages/filelock/_unix.py", line 49, in _release
TypeError: 'NoneType' object is not callable
```

When I remove `/home/dirkg/.cache/tango/wandb_workspace/PredictStep-001-aUzzaKky7tw1rXhp38mMWuboeag8cCGw/lock`, the error comes back.

**Comment by epwalsh** [comment]
Possibly two separate issues here. What version of filelock do you have installed? I see your W&B workspace has [this step](https://wandb.ai/allennlp/catwalk/runs/PredictStep-001-aUzzaKky7tw1rXhp38mMWuboeag8cCGw/overview) already. If you delete it and run again does it work?

**Comment by dirkgr** [comment]
I'm pretty sure you fixed this a while ago? I'll close this and re-open if it comes back.
