### ISSUE TITLE
cached_transformers.get() load_weights arg is not implemented.

### ISSUE THREAD

**Issue by jagnusson** [allenai/catwalk#63]
As noticed by @epwalsh the `load_weights` argument in which is documented in[ cached_transformers.get() ](https://github.com/allenai/catwalk/blob/1c8276da8f71eb7c8b35bbda271133df2a4027d8/catwalk/cached_transformers.py#L61) is not actually implemented. I checked and it is also not a supported kwarg of AutoModel.from_pretrained(). I'll look into supporting this or removing it.

**Comment by epwalsh** [comment]
FWIW, I've found the best way to load a transformer without loading pre-trained weights is to first load the config and then just initialize the model directly with the config. For example:

```python
config = GPT2Config.from_pretrained("gpt2")
model = GPT2LmHeadModel(config)
```

It would probably be fairly easy to add that logic to `cached_transformers`.
