### ISSUE TITLE
trainable_copy might need override_weights_file

### ISSUE THREAD

**Issue by jagnusson** [allenai/catwalk#68]
The `trainable_copy` [method](https://github.com/allenai/catwalk/blob/e9f57427f59b6604b5e59674f0392b9182e9a00d/catwalk/models/rank_classification.py#L109) of `RankClassificationModel` should probably be initialized with its `self.override_weights_file`. This would look like:

```python
def trainable_copy(self) -> TrainableModel:
        return TrainableRankClassificationModel(
            self._make_model(self.pretrained_model_name_or_path, override_weights_file=self.override_weights_file),
            cached_transformers.get_tokenizer(AutoTokenizer, self.pretrained_model_name_or_path),
            self.predict_chunk
        )
```

I need to investigate how `trainable_copy` is used though to make sure this is correct.

**Comment by dirkgr** [comment]
We're passing `self.model_kwargs` to it, so I think this is all good.
